CREATE TABLE IF NOT EXISTS folder_ratings (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  folder_id INTEGER NOT NULL UNIQUE REFERENCES folders(id) ON DELETE CASCADE,
  rating INTEGER NOT NULL,
  rated_at INTEGER NOT NULL
);
