CREATE TABLE IF NOT EXISTS transcripts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  file_id INTEGER NOT NULL UNIQUE REFERENCES files(id) ON DELETE CASCADE,
  text TEXT NOT NULL,
  language TEXT,
  model TEXT NOT NULL,
  created_at INTEGER NOT NULL
);
